/**
 * The test matrix page: every command and option of a commander program, and what exercises it — an
 * offline test that drove it (one `{ command, options }` JSON line per parsed run, written by the
 * CLI under vitest), or a written reason it is not tested offline.
 */

/** The part of commander's `Command` read here; structural, so commander stays an optional peer. */
export interface ProgramNode {
  name(): string
  parent: ProgramNode | null
  commands: readonly ProgramNode[]
  options: readonly { long?: string; short?: string }[]
}

/** `command` ending in ` *` covers every subcommand under it; `""` is the program's own options. */
export interface Untested {
  command: string
  option?: string
  reason: string
}

interface Row {
  command: string
  option?: string
  state: "tested" | "untested" | "missing"
  note: string
}

export const parseArgvLog = (text: string) => {
  const seen = new Map<string, Set<string>>()
  for (const line of text.split("\n")) {
    if (!line) continue
    const { command, options } = JSON.parse(line) as { command: string; options: string[] }
    const known = seen.get(command) ?? new Set<string>()
    for (const option of options) known.add(option)
    seen.set(command, known)
  }
  return seen
}

const runnable = (command: ProgramNode): boolean =>
  (command as unknown as { _actionHandler: unknown })._actionHandler != null

const pathOf = (command: ProgramNode): string => {
  const words: string[] = []
  for (let at: ProgramNode | null = command; at?.parent; at = at.parent) words.unshift(at.name())
  return words.join(" ")
}

const covers = (entry: Untested, command: string) =>
  entry.command === command || (entry.command.endsWith(" *") && command.startsWith(entry.command.slice(0, -1)))

export const matrixRows = (program: ProgramNode, seen: Map<string, Set<string>>, untested: readonly Untested[]) => {
  const skipFor = (command: string, option?: string) =>
    untested.find((entry) => covers(entry, command) && entry.option === option)

  const rows: Row[] = []
  const walk = (command: ProgramNode): void => {
    if (command.parent && runnable(command)) {
      const path = pathOf(command)
      const ran = seen.get(path)
      const skip = skipFor(path)
      rows.push(
        ran
          ? { command: path, state: "tested", note: "" }
          : skip
            ? { command: path, state: "untested", note: skip.reason }
            : { command: path, state: "missing", note: "" },
      )
      for (const option of command.options) {
        const name = option.long ?? option.short ?? ""
        if (name === "--help") continue
        const optionSkip = skipFor(path, name) ?? (skip && !ran ? skip : undefined)
        rows.push(
          ran?.has(name)
            ? { command: path, option: name, state: "tested", note: "" }
            : optionSkip
              ? { command: path, option: name, state: "untested", note: optionSkip.reason }
              : { command: path, option: name, state: "missing", note: "" },
        )
      }
    }
    for (const child of command.commands) walk(child)
  }
  walk(program)

  const globalSeen = new Set([...seen.values()].flatMap((options) => [...options]))
  for (const option of program.options) {
    const name = option.long
    if (!name || name === "--help") continue
    const skip = skipFor("", name)
    rows.push(
      globalSeen.has(name)
        ? { command: "", option: name, state: "tested", note: "" }
        : skip
          ? { command: "", option: name, state: "untested", note: skip.reason }
          : { command: "", option: name, state: "missing", note: "" },
    )
  }

  const stale = untested.filter(
    (entry) => !rows.some((row) => row.option === entry.option && covers(entry, row.command)),
  )
  return { rows, stale }
}

const MARK = { tested: "✅", untested: "⛔", missing: "❌" } as const

export const matrixPage = (rows: readonly Row[], cli: string) => {
  const count = (state: Row["state"]) => rows.filter((row) => row.state === state).length
  const cell = (text: string) => text.replace(/\|/g, "\\|")
  return `<!-- Generated by cli-dev test-matrix from the command tree and a test run. Do not edit; \`pnpm test:matrix\`. -->

# Test matrix

Every command and option of \`${cli}\`, and whether an offline test drives it through the CLI. ✅ a test
ran it · ⛔ not tested offline, with the reason and where it is checked instead · ❌ nothing.
Measured from the test run (\`coverage/argv.jsonl\`), not searched for — see
[TESTING.md](TESTING.md) for how, and for the states and failures that cut across commands.

**${count("tested")} ✅ · ${count("untested")} ⛔ · ${count("missing")} ❌** — ${rows.filter((row) => !row.option).length} commands, ${rows.filter((row) => row.option).length} options.

| Command | Option | | Note |
|---|---|---|---|
${rows
  .map(
    (row) =>
      `| ${row.command ? `\`${row.command}\`` : "*global*"} | ${row.option ? `\`${row.option}\`` : ""} | ${MARK[row.state]} | ${cell(row.note)} |`,
  )
  .join("\n")}
`
}
